#!/usr/bin/env bash
# Write .env: derive what can be derived, ask for the GitLab token once.
set -euo pipefail
# shellcheck source=lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

gitlab_username() {
  glab api user | python3 -c 'import json,sys; print(json.load(sys.stdin)["username"])'
}

azure_subscription_id() {
  az account show --query id -o tsv
}

# An existing .env is overwritten, but never lost: its token may be the only
# copy of a value GitLab will not show again.
backup_existing_env() {
  [ -f "$ENV_FILE" ] || return 0
  cp -p "$ENV_FILE" "$ENV_FILE.bak"
  chmod 600 "$ENV_FILE.bak"
  info "existing .env backed up to .env.bak"
}

ask_for_token() {
  echo "Personal access token with the api scope, created at" >&2
  echo "https://gitlab.com/-/user_settings/personal_access_tokens" >&2
  printf 'Token (nothing is displayed): ' >&2
  read -rs token
  echo >&2
  [ -n "$token" ] || die "empty token."
  printf '%s' "$token"
}

# Checked before it is written down: a wrong value fails much later, with an
# error that says nothing about the token.
check_token() {
  curl -sf --header "PRIVATE-TOKEN: $1" https://gitlab.com/api/v4/user > /dev/null \
    || die "GitLab refused that token. Check that the api scope is set."
}

write_env() {
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh. Gitignored, never commit this file.

export TF_HTTP_USERNAME=$1
export TF_HTTP_PASSWORD=$2

export TF_VAR_subscription_id=$3
EOF
  chmod 600 "$ENV_FILE"
  info ".env written, mode 600."
}

main() {
  require_command glab
  require_command az
  require_command curl

  local user subscription token
  user="$(gitlab_username)"
  subscription="$(azure_subscription_id)"
  info "GitLab user:  $user"
  info "Subscription: $subscription"

  token="$(ask_for_token)"
  check_token "$token"

  backup_existing_env
  write_env "$user" "$token" "$subscription"
}

main "$@"
