#!/usr/bin/env bash
# Create .env from .env.example: derive what can be derived, ask for the GitLab
# token once without echoing it, and refuse to write a token GitLab rejects.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [ -f "$ENV_FILE" ]; then
  echo ".env already exists. Delete it first to start over."
  exit 0
fi

command -v glab > /dev/null || { echo "glab not found." >&2; exit 1; }
command -v az > /dev/null || { echo "az not found." >&2; exit 1; }

GITLAB_USER="$(glab api user | python3 -c 'import json,sys; print(json.load(sys.stdin)["username"])')"
SUBSCRIPTION="$(az account show --query id -o tsv)"

echo "GitLab user:  $GITLAB_USER"
echo "Subscription: $SUBSCRIPTION"
echo
echo "Personal access token with the api scope, created at"
echo "https://gitlab.com/-/user_settings/personal_access_tokens"
printf 'Token (nothing is displayed): '
read -rs TOKEN
echo

[ -n "$TOKEN" ] || { echo "Empty token, aborting." >&2; exit 1; }

# Check the token before writing it down: a wrong value in .env fails later,
# far away from here, with an error that says nothing about the token.
if ! curl -sf --header "PRIVATE-TOKEN: $TOKEN" https://gitlab.com/api/v4/user > /dev/null; then
  echo "GitLab refused that token. Check that the api scope is set." >&2
  exit 1
fi

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh. Gitignored, never commit this file.

export TF_HTTP_USERNAME=$GITLAB_USER
export TF_HTTP_PASSWORD=$TOKEN

export TF_VAR_subscription_id=$SUBSCRIPTION
EOF
chmod 600 "$ENV_FILE"
unset TOKEN

echo ".env written, mode 600."
